### PR TITLE
Release pep spec 2.1.0

### PR DESCRIPTION
**Pull request by nsheff**
This would be a first point release, introducing the concept of versioning the pep spec for real. This adds specifically the multiple sample tables.

Please look at the new "changelog" approach.

### CODE REVIEW

**Comment by stolarczyk** [comment]
I like the idea. But, how do we go about currently released peppy (in fact two versions that have been released) that support multi-subsample tables and allow `pep_version: 2.0.0`?

**Comment by nsheff** [comment]
well, since it's backwards compatible I'm not sure it's a big deal...can you put 2.1.0 and have them still work? or will that break them?

**Comment by stolarczyk** [comment]
yes, It'll work. I made it so the required version is >= 2.0.0, so 2.1.0 is fine.

**Comment by nsheff** [comment]
that's great! Can peppy appropriately respond to different versions of the spec? This is starting to sound like refgenie, isn't it? But in this case we shouldn't update, we just behave slightly differently.

If that's all good, then I think we're fine. In other words, ideally, if you put `2.1.0`, then you're allowed to have multiple subsamples. Otherwise not. But I think in this case it's a small enough change that maybe we just follow that protocol for the next iteration?

**Comment by stolarczyk** [comment]
> that's great! Can peppy appropriately respond to different versions of the spec? 

Now it just checks if `pep_version` is >= 2.0.0 in the object constructor. In the future we can surely make the behavior dependent on the spec version, even in the modifiers.

> ideally, if you put 2.1.0, then you're allowed to have multiple subsamples.

that was my concern, I thought we wanted to enforce this the first time we bump the spec version and just skip the bump for multi `subsample_table`. But I agree, that's a small thing and let's just stick to this plan as we go forward :)

**Review by stolarczyk — APPROVED** [review]

**Comment by nsheff** [comment]
> I thought we wanted to enforce this the first time we bump the spec version and just skip the bump for multi subsample_table. But I agree, that's a small thing and let's just stick to this plan as we go forward :)

that's fine we can do it that way if you like. I can adjust this back to 2.0.0

**Pull request merged**
